version: "3"

services:
  db:
    image: postgres:14-alpine
    container_name: db
    restart: always
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=Silvanaida1
